#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
export HISTFILE=~/.zsh_history
export PATH="$HOME/bin:$PATH"


# Add homebrew to the completion path
fpath=("/usr/local/bin/" $fpath)

# typing dir name cds
setopt AUTO_CD

# This makes cd=pushd
setopt AUTO_PUSHD

export EDITOR="vim"
